/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "pwm.hpp"

#include "tap/algorithms/math_user_utils.hpp"
#include "tap/board/board.hpp"
#include "tap/util_macros.hpp"

using namespace Board;
using namespace tap::algorithms;

namespace tap
{
namespace gpio
{
void Pwm::init()
{
#ifndef PLATFORM_HOSTED

#endif
    // Set all out pins to 0 duty
    writeAllZeros();
}

void Pwm::writeAllZeros()
{
#ifndef PLATFORM_HOSTED
#endif
}

void Pwm::write(float duty, Pin pin)
{
#ifdef PLATFORM_HOSTED
    UNUSED(duty);
    UNUSED(pin);
#else
    duty = limitVal<float>(duty, 0.0f, 1.0f);
    switch (pin)
    {
        default:
            break;
    };
#endif
}

void Pwm::setTimerFrequency(Timer timer, uint32_t frequency)
{
#ifdef PLATFORM_HOSTED
    UNUSED(timer);
    UNUSED(frequency);
#else
    switch (timer)
    {
    }
#endif
}

void Pwm::pause(Timer timer)
{
#ifdef PLATFORM_HOSTED
    UNUSED(timer);
#else
    switch (timer)
    {
    }
#endif
}

void Pwm::start(Timer timer)
{
#ifdef PLATFORM_HOSTED
    UNUSED(timer);
#else
    switch (timer)
    {
    }
#endif
}
}  // namespace gpio

}  // namespace tap
